site_name: GmodHQ Docs
copyright: 'Copyright &copy; 2018 GmodHQ'
docs_dir: mkdocs
site_dir: docs

pages:
  - Home: index.md
  - About: about.md
  - Servers:
    - GoFish: servers/gofish.md
    - DarkRP: servers/darkrp.md
  - Rules: 
    - Global: rules/global.md
    - GoFish: rules/gofish.md
    - DarkRP: rules/darkrp.md



theme:
  name: 'material'
  palette:
    primary: light blue
    accent: blue
  feature:
    tabs: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - type: globe
      link: https://gmodhq.com/
    - type: twitter
      link: https://twitter.com/gmodhq/
    - type: reddit
      link: https://reddit.com/r/gmodhq/

google_analytics:
  - 'UA-119115779-1'
  - 'auto'